uploads = []
generated = []

[[outputs]]
id = "S_2RnMe3IxkZxpRmMWjwL"
uri = "file://shield-mace-mod-release.zip"
type = "unspecified"
title = "Shield Mace Mod 1.1.0 for MC 1.21.11 (Fabric) + Install Guide"

[[outputs]]
id = "WON3PrSO8_RulzG7cii2_"
uri = "file://shield-mace-mod-1.2.0-release.zip"
type = "unspecified"
title = "Shield Mace Mod 1.2.0 — JAR for Minecraft 1.21.11 (Fabric, Java 21)"
